= Explication du dépot - TD 1



== Contenu du dépot

Dans ce dépot, vous pourrez retrouver :

- Une premiere classe java, contenant une premiere fonction de test permettant d'afficher "Hello World"
- Une deuxieme classe java, nommé Geometrie.java. Cette classe contient toute les fonction réalisé lors du premier TP de dev de la première année de DUT. 

Dans la deuxieme classe ce situe toute les fonction permettant de renvoyer des calculs relatif au bon fonctionnement du sujet du TP 1 de dev.



== Pourquoi le dépot fonctionne-t-il?

Pour faire fonctionner le dépot, j'ai modifier le fichier pom.xml afin que la bonne classe soit détecter à la compilation. Nous voulions que le main de la classe Geometrie.java soit prit en compte et non celui de la classe Hellojava.java.

Pour cela, j'ai dans le fichier pom.xml changer le contenu de la balise mainClass par le nom de la classe souhaiter. Cette balise se situe dans la balise manifest.

Voici les modifiecation que j'ai fait pour que le bon main soit détecter :
....
<manifest>
    <mainClass>Geometrie</mainClass>
</manifest>
....

=== Javadoc
 
La javadoc se situe dans le dossier target puis dans site / apidocs. Il vous suffit d'ouvrit le fichier index.html pour l'obetenir sur votre navigateur.

Pour générer cette derniere il fait utiliser la commande :
....
mvn javadoc:javadoc
....

=== Faire fonctionner la classe Geometrie.java

Pour faire fonctionner cette classe, il vous suffit de faire ces deux ligne de code dans la console :
....
mvn package
....

Puis 
....
java -jar target/tp_qualite-1.0.jar
....

Cela vous renverras la surface d'un oval.